
name: Develop Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment: staging
    permissions:
      deployments: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            ${{ vars.REGISTRY_URL }}/app:staging-${{ github.sha }}
            ${{ vars.REGISTRY_URL }}/app:staging-latest
          push: true

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          namespace: staging
          manifests: k8s/staging/
          images: |
            ${{ vars.REGISTRY_URL }}/app:staging-${{ github.sha }}





                  # - name: Rodar Testes
      #   run: docker compose -f docker-compose.ci.yml exec app pytest

      # - name: Lint Code
      #   run: |
      #     docker run --rm \
      #       temp-image:pr-${{ github.event.pull_request.number }} \
      #       sh -c "flake8 && black --check --exclude migrations ."