---
name: Feature Validation

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize]

jobs:
  validate:
    name: Build & Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: ${{ vars.TEST_DB_NAME }}
          POSTGRES_USER: ${{ vars.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: temp-image:pr-${{ github.event.pull_request.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests
        run: |
          docker run --rm \
            --network host \
            -e DB_NAME=${{ vars.TEST_DB_NAME }} \
            -e DB_USER=${{ vars.TEST_DB_USER }} \
            -e DB_PASSWORD=${{ secrets.TEST_DB_PASSWORD }} \
            temp-image:pr-${{ github.event.pull_request.number }} \
            sh -c "./wait-for-db.sh && pytest --cov"

      - name: Lint Code
        run: |
          docker run --rm \
            temp-image:pr-${{ github.event.pull_request.number }} \
            sh -c "flake8 && black --check --exclude migrations ."