---
on:
  pull_request:
    branches:  # Adicione as branches de origem e destino
      - develop  # Branch destino (PR target)
      - main    # Branch destino alternativa
      - 'feature/**'  # Branch de origem (Padrão para features)
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate Feature
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: ${{ vars.TEST_DB_NAME }}
          POSTGRES_USER: ${{ vars.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U ${{ vars.TEST_DB_USER }}" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: temp-image:pr-${{ github.event.pull_request.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Subir Docker Compose
        run: docker-compose -f docker-compose.ci.yml up -d

      - name: Aguardar Banco de Dados
        run: |
          docker-compose -f docker-compose.ci.yml exec app sh -c "./scripts/wait-for-db.sh"

      - name: Rodar Migrações
        run: docker-compose -f docker-compose.ci.yml exec app python manage.py migrate

      - name: Rodar Testes
        run: docker-compose -f docker-compose.ci.yml exec app pytest

      - name: Lint Code
        run: |
          docker run --rm \
            temp-image:pr-${{ github.event.pull_request.number }} \
            sh -c "flake8 && black --check --exclude migrations ."

      - name: Derrubar os containers
        run: docker-compose -f docker-compose.ci.yml down